#!/bin/bash

# JDK 8
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install -y openjdk-8-jdk
echo JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64" >> /etc/environment
source /etc/environment

# Install Elasticsearch
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
sudo apt-get update
sudo apt-get install -y elasticsearch
