#!/bin/bash

# JDK 8
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install -y openjdk-8-jdk
echo JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64" >> /etc/environment
source /etc/environment
